# Generated by Django 2.2.9 on 2019-12-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sportnews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportNews',
            new_name='SportNew',
        ),
    ]
