# Generated by Django 3.0.1 on 2019-12-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191224_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportnew',
            name='sport_choice',
            field=models.CharField(blank=True, choices=[('cri', 'Cri'), ('ftb', 'Ftb')], max_length=50),
        ),
    ]
